### PR TITLE
updated to work on darwin

### PR DESCRIPTION
**Pull request by rsperl**
There were a few attrs and methods that do not exist on macos (sys.platform == "darwin").

### CODE REVIEW

**Review by guettli — CHANGES_REQUESTED** [review]
Thank you very much for your pull request.

I added --output-directory and DUMPENV_OUTPUT_DIRECTORY via environment variable. now.

I have some questions concerning your pull request:

Why do you removed subx?

Why do you want double quotes instead of single quotes?

Please create an issue an show me the stacktrace you get on darwin.
I think I prefer a try..except instead of "if 'darwin': ...."

**Comment by rsperl** [comment]
my bad about the quotes -- I use vscode and have black setup as my formatter, which prefers double quotes over single, so it wasn't something I intended.

`subx` would not install on my mac, so I used the builtin `subprocess` instead.

**Comment by guettli** [comment]
Please open an issue on the subx github page. Please provide the whole error message and how to reproduce it.

**Comment by guettli** [comment]
Could you please provide a new pull request which uses try..exception instead of "if ...". Thank you

**Comment by guettli** [comment]
I updated the code with the suggestions of the pull request. Could you please try the new version which is available on pypi since yesterday. Please tell me if this works now. Thank you.

**Comment by guettli** [comment]
timeout. I received no feedback. Please create a new issue or pull-request if you want to tell me something.

**Pull request closed without merging**
